### ISSUE TITLE
Initial structural suggestions

### ISSUE THREAD

**Issue by trrad** [TheAgoraProject/dta-spec#1]
I had some old thoughts on the best ways to represent the structure of a debate tournament laying around from an unfinished project - so figured I would share some of them here and get things started. It's a topic I've spent many a day prototyping before throwing it all away and moving on with my life. The below document is quite rough, but perhaps a useful first step in framing the problem. This is something I've long felt should be done better, and I'm glad to see people taking steps to do so. Many/most of the people following are more relevantly educated and involved than I am, so I look forward to your thoughts.

Some initial (and general thoughts):
- I too lean slightly more towards XML than JSON. Don't think it's particularly important either way, but find XML generally more readable, and personally prefer working with XML Schemas.
- As a Canadian with basically no international debate exposure, the below will likely run into some issues with formats I'm unfamiliar with. I've done my best to adjust it so the structures can be as loose as possible, but there are some obvious trade-offs I'll do my best to point out along the way.
  - The proposed structure aims to be be as sensible as possible while also not duplicating information unnecessarily.
- I'm paraphrasing some old Python specific writing, so if I misstep and confuse objects/node/element/attribute, please bear with me.
## The Representation(s) - onto the specifics...

There are 4 basic types in my vision of the way this data is stored. Those are **tournament**, **debater**, **judge**, and **round**. Each of these has a unique ID attribute in addition to a collection of sub-elements that define it's properties. I will discuss at the end the value (and tradeoffs) of a **team** structure as well. Each field is intended to be just the basic data -I haven't included any calculations or calculable figures in the interests of Keeping It Simple, and leaving that all to whatever program is reading the file. All data/properties are stored in elements, except for the UniqueID of each element which is kept as an attribute.
### The Tournament

This one is pretty simple. It's the parent elements, to which all the other elements will belong. It contains all <debater>, <judge> and <round> elements and their sub-elements. Additionally, it has it's own elements that define the attributes specific to that tournament. My initial proposal for these are:
- style: Sets the style of the tournament, ie: British Parliamentary, APDA, Australs, etc.
- name: Name of the tournament.
- start_date: The date of the tournament.
- scoring range: defines the available scoring range for that particular tournament (can be broken up into start/end)
- number of rounds: defines the number of in/out rounds at a tournament, likely needs to be broken up.
### Debater

The first type of element used to store data. The properties contained within this are intended to be those that are immutable over the course of the tournament and specific to individuals. It also will have a unique ID attribute by which it is referenced and pointed to.
- name: The debaters name.
- institution: the institution code/name (as noted perhaps some central coordination here).
- roundIDs: a list of all the roundIDs in which the debater participated. The <round> elements will contain all the actual data about what happened AT the tournament.
- rank: the debaters final rank on the speaker tab - in the event that the rounds from a tournament were not recorded, it is possibly to simple enter the debaters rank on the speaker tab.
- novice_status: debater's novice status
- language: define debater's language status in the competition
- gender: debater's gender information
- age: debater's age information
- regional / ethnicity information: possibility to collect.
### Judge

The judge structure contains basically all the same information as the debater, but instead of having the option to include the debaters final ranking, you have the option of publishing the judge's internal ranking.
### The Round

Probably the most interesting & important proposed element. It contains all the data of what actually occurred during debating at the tournament. The data is organized into **Ballot** sub-elements, just like it is in a real-world tournament scenario.
- motion: option to include motion - making it round specific allows for impromptu tournaments as well.
- roundType: details the round type (ie: first round, second round, quarter finals, etc.)
- <ballot>: There can be any number of ballot elements per round. Each ballot can also have any number of Judge IDs associated with it, representing the judges who contributed to that decision. This way, if you have consensus judging, you are able to represent those judges contributing to the decision, or allow for individual submission of ballots. In the event there are multiple ballots, the chair could be specified by order or an additional attribute.
  - within each ballot element there is another element for each debater in the round. This <debaterRanking> element contains the partnerID(s), position (OG, CO, etc.), speaker score and rank (ie: [1-4], [1-2]).

I've included a rough mockup of the proposed below:

``` xml
<tournament>
    <style>British Parlimentary</style>
    <name>Lorem Ipsum Cup</name>
    <start_date>yyyy-mm-dd</start_date>
    <score_range_start>50</score_range_start>
    <score_range_end>90</score_range_end>
    <number_of_rounds>6</number_of_rounds>

    <debater id="debaterID">
        <name>Deborah Debater</name>
        <institution>UNI1</institution>
        <rank>1</rank>
        <novice_status>true</novice_status>
        <gender>Female</gender>
        <age>20</age>
        <language>English</language>
        <roundIDs>RNDA01,RNDB05,RNDC11,etc.</roundIDs>  
    </debater>

    <judge id="judgeID">
        <name>John Judge</name>
        <institution>UNI2</institution>
        <ranking>100</ranking>
        <age>24</age>
        <gender>Male</gender>
        <language>English</language>
        <roundIDs>RNDA03, etc.</roundIDs>
    </judge>

    <round id="roundID">
        <motion>THW standardize debate tab file formats</motion>
        <roundType>1st inround</roundType>

        <ballot judgeIDs="JudgeID1 JudgeID2">
            <debaterRank id="debaterID">
                <partnerID></partnerID>
                <position>Opening Government</position>
                <speaker_score>85</speaker_score>
                <team_rank>1</team_rank>
            </debaterRank>
        </ballot>
    </round>

</tournament>
```
## Discussion

The advantage of this structure is that it (in my view) models the real world quite well, and as a result is relatively easy to understand. In particular, keeping the 'ballot' around as a programmatic representation. This should presumably make it easier to integrate into/export from many tab programs.

Additionally, there is certainly much discussion to still be had regarding exactly how much of the more complex information should be stored at each stage. Some of this could be likely effectively managed by creating slightly different schema for different debate formats. Currently proposed plain-text fields like "roundType" are so vague as to likely be fairly useless in any comparison between - a sensible standard and more rigid type definitions would almost certainly be useful.

However, the fact that under this model the debater's individual results are not attached to the debater object itself may be confusing or not entirely optimal. In my opinion, I'm happier doing it this way and avoid duplication of information across judge/debater/round.
### On Teams

It may make sense to wrap a group of debaters that are on a team in a parent team element. This changes the structure and simplifies some common operations (as the program analyzing/displaying the data doesn't need to create that category on it's own). However, this would prevent (or at least complicate) the recording of tournaments with 'dynamic' teams. I don't know if this is a use case that it's necessary to prepare for.
### More Tournament-Level Definitions

I'm not particularly familiar with many of the styles used - so there may be benefit in encoding much more information in the <tournament> element - such as different scoring systems and options. More controls here could likely do a lot for the extensibility of the format. In particular I imagine fields for defining more details for the "roundType" category would be useful.
### Required Fields

I didn't bother to go through and flag the required vs optional fields. I think it's mostly fairly intuitive, but there may be some different choices/tradeoffs to make there.

... and that's it.

**Comment by czlee** [comment]
This made my day, thanks so much. :smiley: This is a great starting point and isn't too dissimilar to what I had in mind (though much more precise). We'll probably need to split the conversation into subtopics at some point but for now, trying to keep things high-level:
1. I tend to agree that the best strategy for keeping things general is to try to model the real world. Also I appreciate and agree with the provisions to allow for consensus judging and other variations.
2. I hadn't considered dynamic teams but I guess we should be careful not to rule it out. One way to do that without losing the usefulness of grouping teams might just be to allow debaters to be on more than one team, so you end up enumerating all the teams that happen to exist through the tournament? So something like: `<team><debater id="debaterID1" /><debater id="debaterID2" /></team>`, where `debaterID(1|2)` are references to full `<debater>...</debater>` elements elsewhere. Then we could use teams in ballots too.
3. Do you have an opinion on container elements? Say, one for the information at the top (called `<meta>` or `<info>` or something, and then a container `<debaters>` that contains all the `<debater>` elements and so on. (See, _e.g._, [this discussion](http://www.ibm.com/developerworks/xml/library/x-contain/index.html).)
4. How to do cross-referencing (_e.g._ how `debaterID` is used) is a massive question mark for me, but I think modelling each debater and adjudicator (and team) individually, and referencing them by ID is a reasonable strategy. Should there be restrictions placed on what ID can be?
5. I'm also quite happy for debaters' results not to be attached to their objects. I feel like including them in ballots is a richer and more natural way to store information. The XML files themselves wouldn't be read by humans, so if someone wants to read it as a speaker tab, someone should write a tool to convert it. That said, I probably think that partly because that's how Tabbycat stores info. Also, with older tournaments that info is sometimes already lost and only the final speaker tab preserved—should we allow for these by including the option to store scores by debater rather than by ballot?

I had a rough (and not very thorough) mock-up written up at some point but I can't seem to find it now… I'll give it another crack at some point soon.

**Comment by trrad** [comment]
2 - I rewrote this particular paragraph quite a few times trying to come up with a more elegant solution but I think you're right. It also allows an easier inclusion of basic, team-level results (ie: overall ranking) in many scenarios. The nice part of this is now position/ranking information can be shifted to the `<teamResults>` representation within the ballot, and `<roundIDs>` or equivalent can be shifted to the original `<team>` objects, while debaters now have a `<teamIDs>` listing (or whatever the final version looks like)

3 - Given the nature of the structures (a limited number of defined types with many subelements), I think container elements are probably the right way to go.

4 - ID generation doesn't have any intrinsic need to be standardized in my view, although it would likely simplify attempts to collect & standardize data. Given that's much of the motivation behind this project, I think it probably makes sense to develop at least consistent _guidelines_ for how they are formed/what they should contain. Generating them from the name string (or other properties) with some addition to ensure uniqueness (which conveniently can also be accomplished at the schema level) seems most obvious. Any attempt to actually centralize an individual debater's 'PIN' seems likely to require more central oversight than ideal at the format level - although outside services attempting it are certainly a possibility.

5 - I think I prefer the idea of still using the ballot to represent the barest form of the ranking. So you would have a generated 'dummy' round & ballot that contained no judge/round/other debaters/etc. information outside of the linked debater's results (and plausibly their partners) from the round. It does complicate generation in those instances, but a fairly simple standardized tool for turning an archived, limited speaker tab format into this standard would seem like a high-priority project anyway. The consistency of always keeping the expected kinds of information in the expected places is more valuable to me - but that's largely a personal preference.

**Comment by philipbelesky** [comment]
Hey, thanks again for this input. My quick thoughts:

### Tournament Objects
- I think there's a tricky line between attempting to describe a format in the meta data vs having a standardised reference for the format and allowing external tools to interpret that format. For example the number of teams per debate (or even rounds) can be easily inferred from the subsequent data. Even with something like scoring range, I'm not sure what the value would be of having that as meta data is. 

### Debater Objects
- To what end is there a list of rounds that a debater was in? Couldn't those be inferred from the ballot objects later on?
- Including their rank here is also potentially unnecessary as that could be inferred through ballots, although I could see a case for it as a way of allowing for an incomplete but functional tab archive to be easily made from hand tabbed tournament or software without support. In this case maybe a 'final rank score' could be added to aid in this scenario. 

### Adj Objects
- Breaking/not breaking would also be important here. As with debater rank, it could probably be inferred, but it may be useful when break round data is not available.

### Round Objects
- A round should allow for having multiple motions to accomodate motion-choice styles. Each ballot could then specify the motion chosen (and optionally the team's vetoes). 
- How would this ballot format deal with trainees? Its probably important to note their allocations to a debate even if they did not contribute to the decision.
- Perhaps a speakers position should be a simple integer denoted the order in which they spoke and format rules can then produce a human readable name. 
- Is it necessary to denote partners for each speaker? Again that seems like it can be inferred particularly if `debaterRank` also includes their `teamID` (to accomodate instances where an adjudicator might swing or when there are dynamic teams etc).

### Team Objects
- Agree with the above discussion that wrapping debater objects in teams seems like a good idea, and would allow teams to then also have a real name,  rank, rank score, and other meta data.

**Comment by trrad** [comment]
Scoring range is likely still useful as the full range of possible scores may not be reflected in the ones assigned at the tournament - but probably still useful to know. I do agree some of the other meta data should probably be interpreted from the lower level objects.

I also think ranking info in team/debater objects is probably a useful option for entering the barest version of information from a tournament - even if it is possible to interpret in some scenarios.

The rest of your points I fully agree with.

**Comment by philipbelesky** [comment]
Great. In terms of moving this forward, how does this sound:
- We should try and fully resolve any edge cases that would change the basic structure of the format in terms of the broad types of objects to be produce
- We should try and resolve a broad philosophy or strategy in terms of what fields are added for each object. Do we want to be strict and infer information as much as possible? How much do we want to rely on external sources of consistency for institutions and rules? 
- Both of the above would enable us to start drafting a structure for each particular object in the hierarchy (may as seperate issues?)
- There are privacy issues around age, gender and possibly language status that may be worth flagging — I can't see many tournaments providing this data unless in an anonymised form. How we could approach anonymised data may be worth discussing.

**Comment by czlee** [comment]
I'd like to keep this discussion high-level at least at first, lest it sprawl over too many subtopics/into minute details, and I agree that the above questions are sensible first priorities.

**Basic philosophy.** I think there's value in some level of redundancy. Sometimes it's not as inferable as you'd think: for example, formats change over time and I wouldn't count on being able to figure out what the rules were a decade ago. Tournaments might have different methods for ranking speakers, or need to skip ineligible ones, or have very particular one-off circumstances, so it's useful for the tournament's official ranking to be in the archive for the avoidance of doubt.

That said, it's probably possible to take this too far. I originally proposed a (redundant) speaker tab section, but I agree with @trrad that you can generate (possibly incomplete) ballots that do the same thing, and that tools can construct these from speaker tabs. It wouldn't work perfectly with, say, tournaments where judges score individually and average speaks, but since averaging rules might differ between tournaments, maybe the "unified" ballot should also be in there somewhere anyway.

**Edge cases/different formats.** Here's a brainstorm, with _??_ in things I don't know (will update upon discovery):

| Style | Format | Scoring | Judging/Ballots | Motions |
| --- | --- | --- | --- | --- |
| BP | 4 teams of 2 | speaks only, integers, strict order | consensus, one per debate | one per round |
| Australs | 2 teams of 3 + replies | speaks only, integers (½ for replies), strict order | voting, one per judge, average over majority | three per round, teams choose |
| NZ Easters | 2 teams of 2 + replies | speaks only, integers (½ for replies), strict order | voting, one per judge, average over majority | two per round, teams choose |
| NZ Joynt | 2 teams of 3 + replies | speaks only, integers (½ for replies), strict order | voting, one per judge, average over majority | one per round |
| APDA | 2 teams of 2 + replies | speaks and ranks, ¼-points (no reply score), tied-speaks tied-rank wins allowed | voting, one per judge, _not sure about averaging rule_ | no motions (governments run cases) |
| CP | 2 teams of 2 + replies, can merge opp 2nd/reply | _??_ | consensus, one per room | _??_ |
| Aus Easters | 2 teams of 3 | speaks only, integers (½ for replies), strict order | voting, one per judge, average over majority | three per round, teams choose |
| OPD (Germany) | 2 teams of 3 + 3 unaligned speakers | _??_ | _??_ | _??_ |
| Asians | 2 teams of 3 + replies | _??_ | _??_ | _??_ |
| NPDA (America) | _??_ | _??_ | _??_ | _??_ |

There's also non-parliamentary and schools styles (policy, Lincoln-Douglas, public forum, World Schools). I feel like the communities don't really overlap much, but since this is meant to be a technical standard I think it'd be nice to support them all, if we can find a suitable contact.
- **Categories:** Novice, ESL, EFL. Might be useful for these to be abstract labels (rather than `<novice>` or `<language-status>`.
- **Team composition:** Maybe allow for iron-mans? Dynamic teams (e.g., with internal club competitions)?

**Comment by czlee** [comment]
I found the mock-up I did earlier. Have not updated this to account for above discussion, so take with a grain of salt. For example, it should probably make greater use of ID-based cross-referencing.

``` xml
<debating-tournament-archive schema-version="0.1">
    <tournament-info>
        <name>World Universities' Debating Championships</name>
        <code>WUDC</code>
        <style>BP</style>
        <year>2015</year>
        <start-date>2014-12-27</start-date>
        <end-date>2015-01-04</end-date>
        <location>
            <city>Kuala Lumpur</city>
            <country>MY</country>
            <institution code="MY/MARA">Universiti Teknologi Mara</institution>
        </location>
        <categories>
            <category>Open</category>
            <category>ESL</category>
            <category>EFL</category>
        </categories>
    </tournament-info>
    <institutions>
        <institution>
            <code>NZ/AUCK</code>
            <name>University of Auckland</name>
            <country>NZ</country>
        </institution>
    </institutions>
    <teams>
        <team id="NZ/AUCK:1">
            <institution>NZ/AUCK</institution>
            <name>Auckland 1</name>
            <speaker id="GC">Georgia Crawford</speaker>
            <speaker id="WG">Wanda Griffin</speaker>
            <eligible-for>Open</eligible-for>
        </team>
    </teams>
    <adjudicators>
        <adjudicator>
            <institution>US/CT/YALE</institution>
            <name>Levi Flores</name>
        </adjudicator>
    </adjudicators>
    <motions>
        <!-- WUDC -->
        <motion round="1">
            <text>This House regrets the existence of Valentine's Day</text>
            <tag>Valentine's Day</tag>
        </motion>

        <!-- Australs -->
        <motion round="1" id="1A">
            <name>Valentine's Day</name>
            <text>This House regrets the existence of Valentine's Day</text>
            <tag>Valentine's Day</tag>
        </motion>
        <motion round="1" id="1B">
            <name>National days</name>
            <text>This House would abolish national days</text>
            <tag>nationalism</tag>
            <tag>national days</tag>
        </motion>
        <motion round="1" id="1C">
            <name>Christmas</name>
            <text>This House would rename Christmas with a name that is religiously neutral</text>
            <tag>Christmas</tag>
            <tag>religion</tag>
        </motion>
    </motions>
    <debates>
        <!-- WUDC -->
        <debate round="1">
            <team side="og" ref="NZ/AUCK:1" />
            <!-- or -->
            <team side="oo">IIUM A</team>
            <team side="cg">Princeton B</team>
            <team side="co">Belgrade A</team>
            <adjudicator role="chair">Levi Flores</adjudicator>
            <adjudicator role="panellist">Virginia Mccarthy</adjudicator>
            <adjudicator role="panellist">George Willis</adjudicator>
            <result>
                <score side="og" position="1" speaker="Georgia Crawford">77</score>
                <score side="og" position="2" speaker="Wanda Griffin">74</score>
                <winner>Belgrade A</winner>
            </result>
        </debate>

        <!-- Australs -->
        <debate round="1">
            <team side="aff">Victoria 1</team>
            <team side="neg">Monash 2</team>
            <!-- It doesn't really make sense to have both adjudicator and scoresheet elements... -->
            <adjudicator role="chair">Levi Flores</adjudicator>
            <adjudicator role="panellist">Virginia Mccarthy</adjudicator>
            <adjudicator role="panellist">George Willis</adjudicator>
            <scoresheet adjudicator="Levi Flores">
                <score side="aff" position="1">77</score>
                <score side="aff" position="2">75</score>
                <score side="aff" position="3">78</score>
            </scoresheet>
            <result>
                <score side="aff" position="1" speaker="Georgia Crawford">76.66666666667</score>
                <winner>Victoria 1</winner>
            </result>
        </debate>
    </debates>
    <speaker-tab>
        <speaker team="Auckland 1" name="Georgia Crawford">
            <score round="1">77</score>
            <score round="2">79</score>
        </speaker>
    </speaker-tab>
    <team-tab>
        <team>
        </team>
    </team-tab>
</debating-tournament-archive>
```

**Comment by ajcullen** [comment]
Hi all,
Im going to probably be on the Tab team for uow easters next year so should probably get more involved with tab side stuff. Looking through this and I think the first question I need to ask is that whilst using xmls to define types for configurations makes sense I feel that it starts to go beyond defining types to being used to store data based on the above and whilst it might not be an issue in an isolated usage when you are transporting the entire tree, given the intent to be stored as a massive repository as well as in line with what CZ wrote about modularity and accessing specific parts of the data, I think we're overexpanding the role of the xml in this system. 
Would not most of this be stored in an Object Relational Database?

Alex

**Comment by czlee** [comment]
Oh, to clarify, while a massive repository is one potential application, that's not the intent _per se_. It's actually the opposite: the XML is meant to be an interface between systems, so they can exchange data, and so that archive files can sit around without being reliant on their tab system to make sense of them.

So w.r.t. modularity, a massive repository might choose to store it internally as an ORD (for other reasons this is probably a bad idea but modularity-wise it's fine), but the XML is the import and export format. It's just an import/export format that dumps an entire tournament.

A centralised repository might (probably will) spring up, but it's just a follow-on benefit. There might be multiple repositories, or one might spring up to replace a dying one. The idea is not to have the data's longevity reliant on someone indefinitely actively maintaining a website with said database.

Hopefully that sheds more light on what we meant?

**Comment by trrad** [comment]
It seems to be we are broadly settled on the basic structure of:

```
Tournament

 ---- Adjudicator

 ---- Team

 --------- Debater

 ---- Debate

 --------- Ballot
```

with containers where appropriate.

And a decent idea of the type of information that should be related to each object.

In terms of physical analogies & guiding philosophies, a rough set of guidelines that comes to mind would be that the `tournament` representation contains information one might find in a tournament package, `team/debater` what one could find out by asking debaters questions about themselves (and perhaps their overall ranking), and `debate/ballot` by reading the ballot for a given round round.

The 'unified ballot' you mention could perhaps be represented at the `<debate>' or  '<round>` level, or alternatively the averaging information could optionally be included in the meta info.

Exactly what data the tournament object should contain is I think probably the most complex part of the discussion remaining. I like the option of including anonymized statistics, presumably at this level. I also agree with @czlee regarding the value of encoding format information in the tournament object when possible such that it simplifies the process of trying to forensically reconstruct the format from the minimal data. As much as possible we would like to be able to reconstruct the events at a tournament using only this file without reliance on external sources/knowledge.

I think we may be at the point where discussion is better served by separate issues & a more detailed writeup for the tournament level, team/debater level and round/ballot level (or at least _I_ can't think of any additional or insurmountable structure-level issues with the above). There will inevitably some back and forth/cross-talk between those discussions to work out which representation is most appropriate for some particular piece of data - but splitting it up still seems logical to me.

**Comment by czlee** [comment]
To avoid doubt, it's not actually clear to me that that's what the structure should be—as in, I'm not prepare to commit to it yet, right now it's more of a "default" in my mind. For example, if we want to support dynamic teams, then `<debater>` should be a second-level (not third) and `teams` should reference debaters by ID. But I think even the structure relies on our knowing what space we need/want to support.

I was going to propose a discussion split, but I'm not really satisfied that we have a clear idea of our philosophy/strategy for inclusion/exclusion, from which most other decisions derive. Despite what I said before, there's obviously a limit to how much about the format we will include. For example: would the `<tournament-info>` element include the fact that BP has four teams, called OG, OO, CO and OO respectively, and what order they speak in? Or can this be assumed knowledge?

I think the next step after that is figuring out the needs of different tournaments, which I think is non-trivial. I mean, we also need to decide just how far we're going to reach. Is trying to account for Lincoln-Douglas a stretch too far?

What would you think about using the wiki to maintain a "current draft"?

**Comment by czlee** [comment]
Actually, scratch that last sentence, we should probably use the repo itself to maintain a current draft, I guess…

**Comment by trrad** [comment]
That seems reasonable - my main point is I think it would be useful to thread many of these decisions more explicitly/formalize their discussion more clearly and move beyond this single issue's comment thread.

**Comment by ajcullen** [comment]
@czlee that makes a bit more sense then. 

Anyway but to the structure, just thinking about the sorts of variations on a theme we get a tournaments (USU open is currently on, its australs format but teams of 4 where 1 speaker from each team rotates through the judge pool each rounds) and I think @czlee might have a point re: level of `<debaters>` and `<teams>` in terms of how we handle it.
Take two very normal scenarios:
1: Swing speakers and swing teams. Normally just another team created and 3 swing speakers which get allocated scores regardless of who speaks but awful to try and read on a tab to understand how a debate got scored. But also remember these people come from the judge pool usually and so that would mean that it would be possibly useful to account for this in the `<judge>`side of things too.
2. Sometimes teams lose a speaker and have to iron-bench or particularly for 2 day tournaments, rotate in a new person to fill the gap. The norm seems to be that the person who left gets those speaks on the tab, particularly for iron-benches. Obviously varies from tab program to tab program but a thing that comes up.

Anyway, on to splitting the discussion, i think before we split off the structural discussions into the key areas we should really split off two other threads that need to be done first. Requirements (basically tournament formats and scope in/out stuff) and doing our Use cases (and working out edge cases) to help us refine the broader architecture of this spec.

**Comment by czlee** [comment]
Okay, I like @ajcullen's thoughts on what we should do, and I've started files reflecting it:
- styles.md, which lists debate styles and tournament variations
- use-cases.md, which lists what we want to do archives

They're both basically lists, and I think I'm guessing that edge cases and a broader inclusion/exclusion philosophy will follow from both files.

I actually think both exercises are non-trivial. Obviously we won't think of all use cases (part of the point of the project is that we don't know in advance what ideas people will come up with), but we may as well think of what we can. But also, part of the exercise is to decide what we _don't_ want to include in the scope of the project, if there is anything. Listing styles and variations could take a while, with how many there are we'd need quite a few more people to at least tell us a bit more about them.

At least at this stage they're both pretty much brainstorms, so we'll merge pull requests very liberally (_i.e._, feel free to add to those files and submit pull requests, and we'll just merge).

**Comment by tienne-B** [comment]
As a specification has been created and is now in `master`, these initial suggestions for how the format could be constructed is moot. This issue does however have interesting and extensive discussion which could be useful for people looking at this project.
